name: Bot Ordusu

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bot_id: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Botu Calistir
        run: python3 bot.py a581dbde67190beb-34-6-91-209.serveousercontent.com 80
